/*
 * Copyright (c) 2025-2026, Antonio Gabriel Muñoz Conejo <me at tonivade dot es>
 * Distributed under the terms of the MIT License
 */
package com.github.tonivade.diesel;

import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.SOURCE;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Annotation to mark a class as a DSL. This annotation is used to generate the necessary code to implement the DSL.
 *
 * <p>Example usage:</p>
 *
 * <pre>
 * &#64;Diesel
 * public interface Console {
 *  String readLine();
 *  void writeLine(String line);
 * }
 * </pre>
 *
 * This will generate the following code:
 *
 * <pre>
 * import com.github.tonivade.diesel.Program;
 * import javax.annotation.processing.Generated;
 *
 * &#64;Generated("com.github.tonivade.diesel.DieselAnnotationProcessor")
 * public interface ConsoleDsl {
 *
 *   static &lt;S extends Console, E&gt; Program&lt;S, E, String&gt; readLine() {
 *     return Program.effect(Console::readLine);
 *   }
 *
 *   static &lt;S extends Console, E&gt; Program&lt;S, E, Void&gt; writeLine(String line) {
 *     return Program.effect(console -&gt; {
 *       console.writeLine(line);
 *       return null;
 *     });
 *   }
 * }
 * </pre>
 *
 * Then we can use the DSL to create programs like this:
 *
 * <pre>
 * import static ConsoleDsl.*;
 * import static com.github.tonivade.diesel.Program.*;
 *
 * void main() {
 *   var program = pipe(
 *     writeLine("What's your name?"),
 *     _ -&gt; readLine(),
 *     name -&gt; writeLine("Hello, " + name + "!")
 *   );
 *
 *   program.eval(new Console() {
 *     &#64;Override
 *     public void writeLine(String line) {
 *       IO.println(line);
 *     }
 *     &#64;Override
 *     public String readLine() {
 *       return IO.readln();
 *     }
 *   });
 * }
 * </pre>
 *
 * <p>In this example, the interface {@code Console} is marked as DSL. The annotation processor will
 * generate the necessary code to implement programs based on this DSL.</p>
 */
@Retention(SOURCE)
@Target(TYPE)
public @interface Diesel {

  /**
   * Name of the class generated by the annotation processor. By defaul the name will be, {@code name of the class + "Dsl" suffix}.
   *
   * @return name of the class
   */
  String value() default "";

  /**
   * Type of the error that will be used in the generated code.
   *
   * <p>{@code Program<S, E, T>} has three parameters:
   *
   * <ul>
   *   <li>{@code S} is the type of the context</li>
   *   <li>{@code E} is the type of the error</li>
   *   <li>{@code T} is the return type of the operation</li>
   * </ul>
   *
   * By default will be {@code Void} which means it doesn't have an specific error.
   *
   * @return type of the error.
   */
  Class<?> errorType() default Void.class;

}
